

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
  name = "pybind11_bazel",
  strip_prefix = "pybind11_bazel-1943500d97ef8bca7bd4484418602ede67e4a830",
  urls = ["https://github.com/rec-system/pybind11_bazel/archive/1943500d97ef8bca7bd4484418602ede67e4a830.zip"],
)

http_archive(
    name = "rules_python",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.4.0/rules_python-0.4.0.tar.gz",
    sha256 = "954aa89b491be4a083304a2cb838019c8b8c3720a7abb9c4cb81ac7a24230cea",
)

#load("@rules_python//python:repositories.bzl", "py_repositories")
#
#py_repositories()

http_archive(
  name = "pybind11",
  build_file = "@pybind11_bazel//:pybind11.BUILD",
  strip_prefix = "pybind11-2.7.1",
  urls = ["https://github.com/pybind/pybind11/archive/v2.7.1.tar.gz"],
)

load("@pybind11_bazel//:python_configure.bzl", "python_configure")

python_configure(
    name = "pybind_config_python",
    python_version = "3"
)
